### ISSUE TITLE
Issues about reproduce local_prior_match recipe

### ISSUE THREAD

**Issue by nastyZhao** [facebookresearch/flashlight#489] opened 2021-03-08 12:25 UTC
### Question
I want to reproduce local_prior_match recipe in [https://github.com/facebookresearch/wav2letter]()
So my question is if I want to build this project, which version of flashlight is appropriate? The old version flashlight v0.2 or current version can also work? 
Currently I installed flashlight in current version using vcpkg and set CMAKE_INSTALL_PREFIX to my own director.
When I try to build wav2letter the build task failed with following message:

```
-- flashlight found (include:  lib: flashlight::flashlight )
CMake Error at CMakeLists.txt:107 (message):
  flashlight must be build in distributed mode for wav2letter++


-- Configuring incomplete, errors occurred!
```

I can make sure that flashlight is installed with distributed mode on.
I checked relevant issues maybe it is because I did't pass  CMAKE_LIBRARY_PATH and CMAKE_INCLUDE_PATH to my wav2letter build. So I add 
`export CMAKE_INCLUDE_PATH=/home/mydir/local/include/
export CMAKE_LIBRARY_PATH=/home/mydir/local/lib/`
to my bashrc and rebuild the wav2letter, but still the same problem occured.

So is this because the flashlight version is not correct? Or my  CMAKE_LIBRARY_PATH and CMAKE_INCLUDE_PATH didn't pass to the wav2letter build?

**Comment by tlikhomanenko** [comment] 2021-03-10 07:51
Hi, We cannot guarantee reproduction with current flashlight (as we have changed and fixed some bugs), so to reproduce the exact model - please use the exact commits of flashlight and wav2letter specified in the paper repro steps. Otherwise, you could work on reproducing it from current master on your own.

About you build error, could you specify exactly what commits you use both for fl and w2l?

**Comment by nastyZhao** [comment] 2021-03-11 06:44
I see.
I installed the flashlight with commit cccedfe5151e6a56c138d99f19203bbd5f4c8e3f and build the w2l of commit b1d1f89f586120a978a4666cffd45c55f0a2e564.
So I need to build w2l with fl 0.2 release then it will work out.

**Comment by tlikhomanenko** [comment] 2021-03-14 07:18
Yep, flashlight and wav2letter should be consistent: either use both master or use similar time commits (for v0.2 tag there are v0.2 in both repos). Closing for now. Feel free to reopen or create new issue if you have trouble on reproduction (could help navigate you with changes we did since this paper was published).

**Closed by tlikhomanenko** 2021-03-14 07:18 UTC
Labels: question
