### ISSUE TITLE
cuda/ViterbiPath.cuh: No such file or directory with cmake 3.5.1

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/flashlight#200] opened 2020-10-12 04:05 UTC
### Bug Description
Compilation error with ViterbiPath.cu
flashlight/lib/sequence/criterion/cuda/ViterbiPath.cu:8: error: flashlight/lib/sequence/criterion/cuda/ViterbiPath.cuh: No such file or directory

#### Reproduction Steps
git clone (todays master)
Using cmake version 3.5.1:
cmake -DFL_BACKEND=CUDA -DFL_LIBRARIES_USE_CUDA=ON  -DCMAKE_VERBOSE_MAKEFILE=1
make
see compilation failure

### Platform and Hardware
ubuntu 16.04, cuda 10.2, gcc5.4

#### Additional Context
This is due to 
  cuda_include_directories(
    ${CUB_INCLUDE_DIRS}
    $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}/..> # for #include "flashlight/lib"
    )
in repos/flashlight/lib/CMakeLists.txt
which is not resolve as expected : 
/usr/local/cuda/bin/nvcc -M -D__CUDACC__ flashlight/lib/sequence/criterion/cuda/ViterbiPath.cu -o flashlight/debug/CMakeFiles/fl-libraries-cuda.dir/lib/sequence/criterion/cuda/fl-libraries-cuda_generated_ViterbiPath.cu.o.NVCC-depend -ccbin /usr/bin/cc -m64 -Xcompiler ,\"-g\" -std=c++11 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_70,code=compute_70 -gencode arch=compute_75,code=compute_75 -DNVCC -Iflashlight/debug/CUB/src/CUB -I$<BUILD_INTERFACE:flashlight/..> -I/usr/local/cuda/include -I/usr/local/cuda/include

See: -I$<BUILD_INTERFACE:flashlight/..>

Seems to be fixable with simply:
  cuda_include_directories(
    ${CUB_INCLUDE_DIRS}
    ${PROJECT_SOURCE_DIR}/..
    )

**Comment by jacobkahn** [comment] 2020-10-13 21:04
@WilliamTambellini — bleh, sorry about this. I've seen this before a few times, but it's hard to repro. Your fix will fix the issue for `make` - the issue is that `make install` won't work properly in that case (you can try it) because the include path will have a prefix which shouldn't be installed.

Can you run `make install` after building with a clean version of the repo and let me know what happens?

**Comment by WilliamTambellini** [comment] 2020-10-16 22:04
@jacobkahn  Well I could not simply build because both make and make install failed.
Nevermind, it seems to be a cmake thing (bug?) : fails with 3.5.1 but works with 3.13.
The official cmake doc about INTERFACE_INCLUDE_DIRECTORIES
https://cmake.org/cmake/help/v3.5/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html
actually points to 3.5.2, not 3.5.1. Perhaps they fixed a bug in 3.5.2 but FL cmake still accepts 3.5.1 as minimum. CU.

**Comment by jacobkahn** [comment] 2020-11-28 03:11
Closing, as 3.10 is now the minimum required CMake version.

**Closed by jacobkahn** 2020-11-28 03:11 UTC
Labels: bug
