### ISSUE TITLE
Build from the source fails (CPU backend). Docker build successful, all 'make test' failed.

### ISSUE THREAD

**Issue by IliaGrigoriev** [facebookresearch/flashlight#120] opened 2020-05-08 21:42 UTC
Dear Facebook research team,

I'm trying to build the flashlight library from the source on 64 bit Ubuntu 18.04 and it, unfortunately, fails. The build progress varies from time to time - sometimes it gets until 24%, sometimes around 60% or further. Once, the build was completely successful. I could then also successfully carry out the 'make install'. Then, unfortunately, the output from the 'make test' reported all tests failing. I have then decided to erase the build directory inside the flashlight and tried to repeat the build. Ever since I was never again being able to successfully complete the build of the flashlight library from the source.

I could successfully build the flashlight with Docker, yet again the 'cd /root/flashlight/build && make test' returned all tests failing. 

Since the docker build was successful, I decided to give it a shot and see what the wav2letter++ build would return despite the failed tests. The wav2letter++ confirmed finding the flashlight library, yet asked for a distributed version of it. I have a small question regarding this part: "Isn't the flashlight library set by default to build the distributed version? If that is not the case, how do I build a distributed version of the flashlight library with Docker?" 

One thing, that I can't explain, is the output from 'cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU' and, namely, this line: '-- ArrayFire found (include: /opt/arrayfire/include, library: ArrayFire::afcuda)'. I define the backend of the flashlight as CPU, but according to the just mentioned line ArrayFire is set for CUDA backend. My laptop does not have a dedicated graphics card, so there are certainly no Nvidia drivers. I used a .sh installer for ArrayFire version 3.7.1. The question here is: "If that's a mistake, how do I set the flashlight to use the ArrayFire::afcpu?"

Here is the terminal output from the most recent build attempt of the flashlight library from the source:

[flashlight_build_failed_08_05_2020.txt](https://github.com/facebookresearch/flashlight/files/4601804/flashlight_build_failed_08_05_2020.txt)

I would be very grateful if you could help me out on this matter. And many thanks in advance for your attention.

Best regards, 
Ilia

**Comment by tlikhomanenko** [comment] 2020-05-09 22:35
Hi @IliaGrigoriev,

About running the tests: this is a problem with mkl and its linking. You need to do export:
```
export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64:$LD_IBRARY_PATH
```
before running tests (the same you need to run in the docker container).

About arrayfire: there should be line like this during cmake `-- ArrayFire found (include: /usr/local/include, library: ArrayFire::afcpu)`, which means that you didn't install cpu backend of arrayfire. You can have a look here https://github.com/facebookresearch/flashlight/blob/master/Dockerfile-CPU-Base#L67 how we install it for CPU backend in the docker.

At first, could you try docker container and run tests with the above mkl export I mentioned?

**Comment by IliaGrigoriev** [comment] 2020-05-11 17:17
Hi @tlikhomanenko ,

many thanks for your swift reply. I have tried out the following steps:

(1) export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2020.0.166/linux/mkl/lib/intel64:$LD_IBRARY_PATH

(2) Then the lines 63-68 from https://github.com/facebookresearch/flashlight/blob/master/Dockerfile-CPU-Base

(3) sudo docker run --rm -itd --name flashlight flml/flashlight:cpu-lates

(4)  sudo docker exec -it flashlight bash

(5) export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2020.0.166/linux/mkl/lib/intel64:$LD_IBRARY_PATH

(6) cd /root/flashlight/build && make test

The output was, unfortunately, all tests failing. 

I was very curious about CPU backend installation for the ArrayFire after executing step (2), so I have also tried again to build the flashlight from the source with 'cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU'. In the cmake output I saw the line `-- ArrayFire found (include: /usr/local/include, library: ArrayFire::afcpu)  `. Next, I launched `make`. The `make` step failed with the same output as before. 

Do you know what could I try next to install a distributed flashlight library?

Many thanks for your support and your time.

Best regards, 
Ilia

**Comment by tlikhomanenko** [comment] 2020-05-13 05:35
@IliaGrigoriev,

Hmm, why do export 2020 mkl? Inside docker this works for me (inside it we have 2018 version) `export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64:$LD_IBRARY_PATH`. Please try this version inside docker.

For the local installation (from source) could you attach the latest log with cmake and make when correct afcpu is linked?

**Comment by IliaGrigoriev** [comment] 2020-05-17 23:40
Hi @tlikhomanenko ,

I'm sorry for the delay with my feedback. I have installed the mkl library version 2018.5.274 as described here: https://software.intel.com/content/www/us/en/develop/articles/installing-intel-free-libs-and-python-apt-repo.html  I used the version 2018, update 4 and build number 057. 

Here is the output from the docker:
[docker_inst_output_17_05_2020.txt](https://github.com/facebookresearch/flashlight/files/4641275/docker_inst_output_17_05_2020.txt)

I have then tried to build the flashlight library from the source, after linking the mkl version from 2018 the `sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU -DFL_BUILD_DISTRIBUTED=ON` reports that MKL library is not found. I have also tried exporting the MKL pass as in the tutorial: https://fl.readthedocs.io/en/latest/installation.html#cpu-backend-dependencies. Unfortunately, this time `export MKLROOT=/opt/intel/mkl` did not help anymore - `sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU -DFL_BUILD_DISTRIBUTED=ON` reported: MKL library is not found. That export used to work and MKL used to be found.

The output from the build attempt of flashlight library from the source:
[build_from_source_output_17_05_2020.txt](https://github.com/facebookresearch/flashlight/files/4641306/build_from_source_output_17_05_2020.txt)

Many thanks again for your support.

Best regards, 
Ilia

**Comment by tlikhomanenko** [comment] 2020-05-23 20:20
Ok, let's solve at first the problem with docker. Can you load the latest docker image we published and then start container, go to it and do 
```
export LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.5.274/linux/mkl/lib/intel64:$LD_IBRARY_PATH
cd /root/flashlight/build
make test
```
If you see still the error for the test, could you just separately run "AutogradTest" for example, to see exactly what is the crash.

FYI: you don't need to install anything outside and inside the docker image (outside doesn't influence the docker image, except cuda drivers, and inside the image we installed everything you need for the flashlight build). I have tested on my side, it works fine, so this should work for you too.

**Comment by tlikhomanenko** [comment] 2020-05-23 20:21
For local installation, please check what is in the `/opt/intel/mkl` and what is in the `/opt/intel/` - possibly it cannot find because two versions are installed.

**Comment by IliaGrigoriev** [comment] 2020-05-25 15:40
Hi, 

thank you again for your feedback. I have followed this webpage to get the latest docker for flashlight: https://hub.docker.com/r/flml/flashlight/tags?page=1

I have tried `cpu-latest` and `cpu-e0bf8f5`. In both cases, I get the same result. Here is the output from the docker, when I run `sudo docker run --rm -itd --name flashlight flml/flashlight:cpu-e0bf8f5` (this output also includes at the end the output from the separate run of the  "AutogradTest"):

[docker_build_and_tests_25_05_2020.txt](https://github.com/facebookresearch/flashlight/files/4677903/docker_build_and_tests_25_05_2020.txt)

The failure from `AutogradTest` reports: "rnn not yet implemented on CPU"

Thank you a lot for the suggestion to take a closer look at the fact, that I have two MKL versions installed. That can, of course, create conflicts. I have had my symbolic links still set pointing to MKL library from 2020. I have now removed the MKL library of 2020 with `sudo rm -r` from the /opt/intel/ folder and updated the symbolic links to point at the MKL library from 2018. This is how my symbolic links in the /opt/intel/ folder look like now: 

```
(base) ilia@ilia-ThinkPad-T480s:/opt/intel$ ls -l
total 32
drwxr-xr-x 2 root root 4096 Mai 17 20:35 bin
lrwxrwxrwx 1 root root   28 Mai 25 11:09 compilers_and_libraries -> compilers_and_libraries_2018
drwxr-xr-x 3 root root 4096 Mai 17 20:35 compilers_and_libraries_2018
drwxr-xr-x 4 root root 4096 Mai 17 20:34 compilers_and_libraries_2018.5.274
drwxr-xr-x 6 root root 4096 Mär 25 12:18 conda_channel
drwxr-xr-x 4 root root 4096 Mai 17 20:34 documentation_2018
drwxr-xr-x 2 root root 4096 Mär 16 20:52 lib
lrwxrwxrwx 1 root root   33 Mai 17 20:35 mkl -> compilers_and_libraries/linux/mkl
lrwxrwxrwx 1 root root   29 Mai 17 20:35 parallel_studio_xe_2018 -> parallel_studio_xe_2018.4.057
drwxr-xr-x 5 root root 4096 Mai 17 20:35 parallel_studio_xe_2018.4.057
drwxr-xr-x 3 root root 4096 Mai 17 20:35 samples_2018
lrwxrwxrwx 1 root root   33 Mai 17 20:35 tbb -> compilers_and_libraries/linux/tbb
```

The output from the `sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU -DFL_BUILD_DISTRIBUTED=ON` is:

[build_from_source_output_25_05_2020.txt](https://github.com/facebookresearch/flashlight/files/4677909/build_from_source_output_25_05_2020.txt)

Many thanks again.

All the best, 
Ilia

**Comment by tlikhomanenko** [comment] 2020-05-26 23:02
@IliaGrigoriev 

Some parts of flashlight are not implemented yet for CPU, like RNN - so this is expected error. Just check that all the errors you see on the each test are "not implemented" (so part of the test will be failed because we just throw exception on non-implemented right now) and the rest pass.

Ok, I reproduced the same behaviour for the latest master you posted in docker container. It crashes at the end of each test (inside the tests could fail due to not-implemented yet thing, but the rest are fine, you can check by yourself). Checking the reason of this crash (possible due to some memory manager changes recently). Thanks!  The rest is ok, so you can try to use this container to run the training. Let me know if something is weird there.

For the mkl issue on local installation, could you try to do this https://github.com/facebookresearch/wav2letter/issues/143#issuecomment-457102430?

**Comment by IliaGrigoriev** [comment] 2020-06-09 16:50
Hi @tlikhomanenko,

as always, thank you for your feedback. The goal is to build wav2letter++ and I could successfully run the build of the wav2letter++ from the docker, so I had to leave flashlight build attempts until now. 

(a) Now that I have come back to flashlight build, I ran all the tests separately and, unfortunately, there are more error reports. To summarize the errors are - dumped cores and memory allocation failures and this one:
 "/root/flashlight/tests/nn/NNSerializationTest.cpp:275: Failure
Value of: allClose(leNet2->forward(in), leNet->forward(in))
  Actual: false
Expected: true
[  FAILED  ] NNSerializationTest.LeNet (25 ms)"

All error outputs in txt file: 
[docker_flashlight_tests_output_09_06_2020.txt](https://github.com/facebookresearch/flashlight/files/4753405/docker_flashlight_tests_output_09_06_2020.txt)

(b) Regarding the build from the source. I have tried the suggestion from https://github.com/facebookresearch/wav2letter/issues/143#issuecomment-457102430 and if you call `cmake` inside the wav2letter++ build directory the MKL library is recognized, but for flashlight library, this is not the case. 

The output from the build attempts from the source: 
[flashlight_wav2letter_source_cmake_09_06_2020.txt](https://github.com/facebookresearch/flashlight/files/4753532/flashlight_wav2letter_source_cmake_09_06_2020.txt)

Many thanks for your support.

Best wishes, 
Iliá

**Comment by tlikhomanenko** [comment] 2020-06-18 05:15
@IliaGrigoriev, the code which cause the Test seg fault is moved out, so now it should pass tests except "not implemented yet" (in the commit 023af073e97701308864a43447bd25b1528848ca), could you try latest master?

> (b) Regarding the build from the source. I have tried the suggestion from [facebookresearch/wav2letter#143 (comment)](https://github.com/facebookresearch/wav2letter/issues/143#issuecomment-457102430) and if you call `cmake` inside the wav2letter++ build directory the MKL library is recognized, but for flashlight library, this is not the case.
> 
> The output from the build attempts from the source:
> [flashlight_wav2letter_source_cmake_09_06_2020.txt](https://github.com/facebookresearch/flashlight/files/4753532/flashlight_wav2letter_source_cmake_09_06_2020.txt)

@jacobkahn any idea how to fix problem of mkl visibility here?

**Comment by tlikhomanenko** [comment] 2020-06-20 03:43
Still the core dump exist, reported in the https://github.com/facebookresearch/wav2letter/issues/706.

**Comment by jacobkahn** [comment] 2020-07-20 17:30
Closing, will track in https://github.com/facebookresearch/wav2letter/issues/706. Needs to be fixed, but the backend will still work fine.

**Closed by jacobkahn** 2020-07-20 17:30 UTC
