### ISSUE TITLE
[making wav2letter compatible with cuda 11.1]

### ISSUE THREAD

**Issue by LamyaMohamed** [facebookresearch/flashlight#377] opened 2020-12-28 12:41 UTC
Hello,
cuda11.1 is the latest version of cuda, can you please make wav2letter compatible with it?

**Comment by jacobkahn** [comment] 2020-12-28 17:57
Duplicate of https://github.com/facebookresearch/flashlight/issues/357. Will track in that.

**Closed by jacobkahn** 2020-12-28 17:57 UTC
